### ISSUE TITLE
The CI `Setup Go` version condition is blank

### ISSUE THREAD

**Issue by Aisuko** [layer5io/meshery-linkerd#51]
**Description**
A brief description of the issue.

I saw the version of go is blank so I'm not sure which version go we used and may the CI `tools` may not compatible correctly with the specific version e.g `gosec` just change the go version with the PR 

https://github.com/layer5io/meshery-linkerd/runs/569837091?check_suite_focus=true

The CI file 

```
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ secrets.GO_VERSION }}
```

So the `secrets.GO_VERSION` should have the right value 

**Expected Behavior**
A brief description of what you expected to happen.

I believe the version should follow the `go.mod` under the root folder of the project and should be as a dynamic parameter

**Screenshots**
Add screenshots, if applicable, to help explain your problem.

**Enviroment:**
 - OS: [e.g. Ubuntu]
 - Browser: [e.g. Chrome, Safari]
 - Version: [e.g. 22]
 - Device: [e.g. laptop, iPhone 8]

---
[Optional] **To Reproduce**

[Optional] **Additional Context**
